title: "Ana Blanco Delgado"
email: anablancodelgado@gmail.com
timezone: UTC+1
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo_ana.svg'
favicon: 'assets/images/favicon_ana.ico'
author: Ana
paginate: 30
disqus: 'demowebsite'
locale: es_es
lang: es_es
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  ana:
    name: Ana
    display_name: Ana
    # avatar: 'assets/images/sal.png'
    email: anablancodelgado@gmail.com
    linkedin: https://www.linkedin.com/in/anablancodelgado/
    web: https://casiopa.github.io/
    description: "Visual artist & data scientist"
  
    
# Social
social:
  github: https://github.com/casiopa
  linkedin: https://www.linkedin.com/in/anablancodelgado/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives