title: "Pablo Faura Sanz | Data Science Portfolio"
email: pfaur.data@gmail.com
timezone: UTC+1
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo_ana.svg'
favicon: 'assets/images/favicon.ico'
author: Pablo Faura Sanz
paginate: 30
disqus: 'demowebsite'
locale: es_es
lang: es_es
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  pablo:
    name: Pablo Faura Sanz
    display_name: Pablo
    avatar: 'assets/images/avatar.png'
    email: pfaur.data@gmail.com
    linkedin: https://www.linkedin.com/in/pablo-faura-sanz-datascience-mba
    web: https://pablof13.github.io/
    description: "Data scientist Jr"
  

# Social
social:
  github: https://github.com/pablof13
  linkedin: https://www.linkedin.com/in/pablo-faura-sanz-datascience-mba

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
